(eval-when-compile    (require 'color-theme))
(defun color-theme-mac-novel ()
  "Color theme by nominolo, created 2010-02-01."
  (interactive)
  (color-theme-install
   '(color-theme-mac-novel
     ((background-color . "#dfdbc3")
      (background-mode . light)
      (background-toolbar-color . "#cf3ccf3ccf3c")
      (border-color . "Grey")
      (bottom-toolbar-shadow-color . "#79e77df779e7")
      (cua-global-mark-cursor-color . "cyan")
      (cua-normal-cursor-color . "black")
      (cua-overwrite-cursor-color . "yellow")
      (cua-read-only-cursor-color . "darkgreen")
      (cursor-color . "red3")
      (ebnf-except-border-color . "Black")
      (ebnf-line-color . "Black")
      (ebnf-non-terminal-border-color . "Black")
      (ebnf-repeat-border-color . "Black")
      (ebnf-special-border-color . "Black")
      (ebnf-terminal-border-color . "Black")
      (foreground-color . "black")
      (howm-use-color . t)
      (mouse-color . "Grey")
      (ps-line-number-color . "black")
      (ps-zebra-color . 0.95)
      (senator-eldoc-use-color . t)
      (term-default-bg-color . unspecified)
      (term-default-fg-color . unspecified)
      (top-toolbar-shadow-color . "#fffffbeeffff")
      (viper-saved-cursor-color-in-replace-mode . "Red3")
      (whitespace-display-spaces-in-color . t))
     ((apropos-keybinding-face . underline)
      (apropos-label-face . italic)
      (apropos-match-face . match)
      (apropos-property-face . bold-italic)
      (apropos-symbol-face . bold)
      (compilation-message-face . underline)
      (ebnf-except-border-color . "Black")
      (ebnf-line-color . "Black")
      (ebnf-non-terminal-border-color . "Black")
      (ebnf-repeat-border-color . "Black")
      (ebnf-special-border-color . "Black")
      (ebnf-terminal-border-color . "Black")
      (ispell-highlight-face . flyspell-incorrect)
      (list-matching-lines-buffer-name-face . bold)
      (list-matching-lines-face . bold)
      (org-goto-interface . outline)
      (org-remember-interactive-interface . refile)
      (preview-transparent-color highlight :background)
      (ps-line-number-color . "black")
      (ps-zebra-color . 0.95)
      (rmail-highlight-face . rmail-highlight)
      (term-default-bg-color . "gray20")
      (term-default-fg-color . "gray70")
      (tetris-use-color . t)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "white" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal))))
     (Info-title-1-face ((t (:bold t :weight bold :height 1.728 :family "helv"))))
     (Info-title-2-face ((t (:bold t :weight bold :height 1.44 :family "helv"))))
     (Info-title-3-face ((t (:bold t :weight bold :height 1.2 :family "helv"))))
     (Info-title-4-face ((t (:bold t :weight bold :family "helv"))))
     (action-lock-face ((t (:background "gray40" :foreground "yellow"))))
     (antlr-font-lock-keyword-face ((t (:bold t :weight bold :foreground "black"))))
     (antlr-font-lock-literal-face ((t (:bold t :foreground "Gray85" :weight bold))))
     (antlr-font-lock-ruledef-face ((t (:bold t :foreground "Gray85" :weight bold))))
     (antlr-font-lock-ruleref-face ((t (:foreground "Gray85"))))
     (antlr-font-lock-tokendef-face ((t (:bold t :foreground "Gray85" :weight bold))))
     (antlr-font-lock-tokenref-face ((t (:foreground "Gray85"))))
     (bbdb-company ((t (nil))))
     (bbdb-field-name ((t (nil))))
     (bbdb-field-value ((t (nil))))
     (bbdb-name ((t (nil))))
     (bg:erc-color-face0 ((t (nil))))
     (bg:erc-color-face1 ((t (nil))))
     (bg:erc-color-face10 ((t (nil))))
     (bg:erc-color-face11 ((t (nil))))
     (bg:erc-color-face12 ((t (nil))))
     (bg:erc-color-face13 ((t (nil))))
     (bg:erc-color-face14 ((t (nil))))
     (bg:erc-color-face15 ((t (nil))))
     (bg:erc-color-face2 ((t (nil))))
     (bg:erc-color-face3 ((t (nil))))
     (bg:erc-color-face4 ((t (nil))))
     (bg:erc-color-face5 ((t (nil))))
     (bg:erc-color-face6 ((t (nil))))
     (bg:erc-color-face7 ((t (nil))))
     (bg:erc-color-face8 ((t (nil))))
     (bg:erc-color-face9 ((t (nil))))
     (blank-space-face ((t (:background "LightGray"))))
     (blank-tab-face ((t (:background "Wheat"))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:bold t :weight bold))))
     (border ((t (:background "Grey"))))
     (border-glyph ((t (nil))))
     (buffer-menu-buffer ((t (nil))))
     (buffers-tab ((t (:background "gray30" :foreground "LightSkyBlue"))))
     (button ((t (nil))))
     (c-nonbreakable-space-face ((t (:background "gray90" :foreground "gray30" :underline "red"))))
     (calendar-today ((t (:underline t))))
     (cell-action-face ((t (:bold t :background "red" :foreground "yellow" :weight bold))))
     (cell-axis-face ((t (:background "gray25" :foreground "gray45" :box (:line-width 1 :color "gray35")))))
     (cell-axis-odd-face ((t (:background "gray23" :foreground "gray42" :box (:line-width 1 :color "gray34")))))
     (cell-bang-face ((t (:bold t :background "red" :foreground "cyan" :weight bold))))
     (cell-blank-face ((t (:background "gray20" :foreground "white" :box (:line-width 1 :color "gray35")))))
     (cell-blank-odd-face ((t (:background "gray18" :foreground "gray99" :box (:line-width 1 :color "gray34")))))
     (cell-comment-face ((t (:italic t :foreground "white" :slant italic))))
     (cell-compute-cursor-face ((t (:box (:line-width 1 :color "purple")))))
     (cell-cursor-face ((t (:background "yellow" :foreground "black"))))
     (cell-default-face ((t (:foreground "white"))))
     (cell-elisp-face ((t (:background "OliveDrab" :foreground "white"))))
     (cell-file-face ((t (:foreground "yellowgreen"))))
     (cell-keyword-face ((t (:background "DarkOrchid4" :foreground "white" :box (:line-width 1 :color "gray35")))))
     (cell-lisp-face ((t (:background "white" :foreground "gray50"))))
     (cell-print-face ((t (:background "gray40" :foreground "gray80"))))
     (cell-receive-var-face ((t (:background "mediumblue" :foreground "white"))))
     (cell-selection-face ((t (:background "seagreen" :foreground "cyan"))))
     (cell-send-var-face ((t (:background "mediumblue" :foreground "white"))))
     (cell-subr-face ((t (:background "white" :foreground "gray40"))))
     (cell-text-face ((t (:foreground "yellow"))))
     (cell-wiki-face ((t (:background "darkslateblue" :foreground "white"))))
     (change-log-acknowledgement ((t (:foreground "gray48"))))
     (change-log-acknowledgement-face ((t (:foreground "gray48"))))
     (change-log-conditionals ((t (:foreground "grey50"))))
     (change-log-conditionals-face ((t (:foreground "grey50"))))
     (change-log-date ((t (:background "gray17" :foreground "gray60"))))
     (change-log-date-face ((t (:background "gray17" :foreground "gray60"))))
     (change-log-email ((t (:foreground "grey50"))))
     (change-log-email-face ((t (:foreground "grey50"))))
     (change-log-file ((t (:foreground "gold"))))
     (change-log-file-face ((t (:foreground "gold"))))
     (change-log-function ((t (:foreground "grey50"))))
     (change-log-function-face ((t (:foreground "grey50"))))
     (change-log-list ((t (:foreground "gray50"))))
     (change-log-list-face ((t (:foreground "gray50"))))
     (change-log-name ((t (:foreground "gold"))))
     (change-log-name-face ((t (:foreground "gold"))))
     (chess-display-black-face ((t (nil))))
     (chess-display-white-face ((t (nil))))
     (cmode-bracket-face ((t (nil))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:bold t :foreground "RoyalBlue4" :background "lightsteelblue1" :weight bold))))
     (comint-input-face ((t (:foreground "deepskyblue3"))))
     (compilation-column-number ((t (:foreground "DarkOrange1" :underline nil))))
     (compilation-error ((t (:underline "red"))))
     (compilation-info ((t (:bold t :background "grey90" :weight bold))))
     (compilation-info-face ((t (:bold t :foreground "Green" :weight bold))))
     (compilation-line-number ((t (:foreground "grey55"))))
     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
     (compilation-warning-face ((t (:bold t :foreground "Orange" :weight bold))))
     (completions-common-part ((t (nil))))
     (completions-first-difference ((t (nil))))
     (cperl-array-face ((t (:bold t :foreground "light salmon" :weight bold))))
     (cperl-hash-face ((t (:italic t :bold t :foreground "beige" :slant italic :weight bold))))
     (cperl-invalid-face ((t (:foreground "white"))))
     (cperl-nonoverridable-face ((t (:foreground "aquamarine"))))
     (css-property ((t (:foreground "sienna"))))
     (css-selector ((t (:foreground "RoyalBlue4" :background "lightsteelblue1"))))
     (cua-global-mark-face ((t (nil))))
     (cua-rectangle-face ((t (nil))))
     (cua-rectangle-noselect-face ((t (nil))))
     (cursor ((t (:background "red3"))))
     (custom-button ((t (:background "grey95" :box (:line-width 1 :color "grey75" :style released-button)))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:foreground "violet" :underline t))))
     (custom-button-unraised ((t (:underline t))))
     (custom-changed ((t (:background "blue" :foreground "white"))))
     (custom-comment ((t (:background "dim gray"))))
     (custom-comment-tag ((t (:foreground "gray80"))))
     (custom-documentation ((t (:foreground "gray40"))))
     (custom-face-tag ((t (:underline t))))
     (custom-group-tag ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (custom-group-tag-1 ((t (:foreground "pale turquoise" :underline t))))
     (custom-invalid ((t (:background "red" :foreground "yellow"))))
     (custom-link ((t (:foreground "blue3" :underline t))))
     (custom-modified ((t (:background "blue" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue"))))
     (custom-state ((t (:foreground "light salmon"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:bold t :foreground "blue3" :weight bold))))
     (cvs-filename-face ((t (:foreground "white"))))
     (cvs-handled-face ((t (:foreground "pink"))))
     (cvs-header-face ((t (:foreground "green"))))
     (cvs-marked-face ((t (:bold t :foreground "green3" :weight bold))))
     (cvs-msg-face ((t (:foreground "gray85"))))
     (cvs-need-action-face ((t (:foreground "yellow"))))
     (cvs-unknown-face ((t (:foreground "grey"))))
     (cyan ((t (:foreground "cyan"))))
     (darcsum-change-line-face ((t (:background "grey90"))))
     (darcsum-filename-face ((t (:inherit font-lock-function-name-face))))
     (darcsum-header-face ((t (:bold t :foreground "lightyellow" :weight bold))))
     (darcsum-marked-face ((t (:bold t :weight bold))))
     (darcsum-need-action-face ((t (:foreground "orange"))))
     (darcsum-need-action-marked-face ((t (:bold t :foreground "orange" :weight bold))))
     (darcsum-whitespace-ateol-face ((t (:background "#f66"))))
     (diary ((t (:foreground "yellow"))))
     (diary-button-face ((t (nil))))
     (dictionary-button-face ((t (nil))))
     (dictionary-reference-face ((t (nil))))
     (dictionary-word-entry-face ((t (nil))))
     (diff-added ((t (:background "#dfd" :foreground "green4"))))
     (diff-added-face ((t (:background "#dfd" :foreground "green4"))))
     (diff-changed ((t (:foreground "gold3"))))
     (diff-changed-face ((t (:foreground "gold3"))))
     (diff-context ((t (nil))))
     (diff-context-face ((t (nil))))
     (diff-file-header ((t (:weight bold))))
     (diff-file-header-face ((t (:weight bold))))
     (diff-function ((t (nil))))
     (diff-function-face ((t (nil))))
     (diff-header ((t (nil))))
     (diff-header-face ((t (nil))))
     (diff-hunk-header ((t (:background "gray90"))))
     (diff-hunk-header-face ((t (:background "gray90"))))
     (diff-index ((t (nil))))
     (diff-index-face ((t (nil))))
     (diff-indicator-added ((t (nil))))
     (diff-indicator-changed ((t (nil))))
     (diff-indicator-removed ((t (:foreground "tomato4"))))
     (diff-nonexistent ((t (nil))))
     (diff-nonexistent-face ((t (nil))))
     (diff-removed ((t (:background "#fdd" :foreground "red3"))))
     (diff-removed-face ((t (:background "#fdd" :foreground "red3"))))
     (dired-directory ((t (:bold t :inherit font-lock-function-name-face :weight bold))))
     (dired-face-boring ((t (:foreground "Gray65"))))
     (dired-face-directory ((t (:bold t :foreground "sky blue" :weight bold))))
     (dired-face-executable ((t (:foreground "green yellow"))))
     (dired-face-flagged ((t (:foreground "tomato"))))
     (dired-face-header ((t (:background "grey75" :foreground "gray30"))))
     (dired-face-marked ((t (:italic t :foreground "slate gray" :slant italic))))
     (dired-face-permissions ((t (:foreground "aquamarine"))))
     (dired-face-setuid ((t (:foreground "gray85"))))
     (dired-face-socket ((t (:foreground "gray85"))))
     (dired-face-symlink ((t (:foreground "cyan"))))
     (dired-flagged ((t (nil))))
     (dired-header ((t (:bold t :weight bold :height 1.44 :family "helv"))))
     (dired-ignored ((t (:foreground "gray50"))))
     (dired-mark ((t (nil))))
     (dired-marked ((t (:background "grey90"))))
     (dired-perm-write ((t (:foreground "gray40"))))
     (dired-symlink ((t (:foreground "IndianRed1"))))
     (dired-warn-writable ((t (:underline "red"))))
     (dired-warning ((t (nil))))
     (display-time-mail-balloon-enhance-face ((t (:background "orange" :foreground "black"))))
     (display-time-mail-balloon-gnus-group-face ((t (:foreground "blue"))))
     (display-time-time-balloon-face ((t (:foreground "gray85"))))
     (ebrowse-default-face ((t (nil))))
     (ebrowse-file-name-face ((t (:italic t :slant italic))))
     (ebrowse-member-attribute-face ((t (:foreground "red"))))
     (ebrowse-member-class-face ((t (:foreground "Gray85"))))
     (ebrowse-progress-face ((t (:background "blue"))))
     (ebrowse-root-class-face ((t (:bold t :foreground "Gray85" :weight bold))))
     (ebrowse-tree-mark-face ((t (:foreground "Gray85"))))
     (ecaspace-io-face ((t (:background "navyblue" :foreground "cyan"))))
     (ecaspace-monitor-p-face ((t (:background "forestgreen" :foreground "yellow"))))
     (ecaspace-next-take-face ((t (:background "white" :foreground "red"))))
     (ecaspace-record-p-face ((t (:background "red" :foreground "yellow"))))
     (ecaspace-selected-take-face ((t (:background "gray20" :foreground "white"))))
     (ecaspace-track-face ((t (:background "white" :foreground "gray50"))))
     (ecb-bucket-token-face ((t (:bold t :weight bold))))
     (ecb-default-general-face ((t (:height 1.0))))
     (ecb-default-highlight-face ((t (:background "magenta" :height 1.0))))
     (ecb-directories-general-face ((t (:height 0.9))))
     (ecb-directory-face ((t (:background "Cyan4"))))
     (ecb-history-face ((t (:background "Cyan4"))))
     (ecb-history-general-face ((t (:height 0.9))))
     (ecb-method-face ((t (:background "Cyan4" :slant normal :weight normal))))
     (ecb-methods-general-face ((t (:slant normal))))
     (ecb-source-face ((t (:background "Cyan4"))))
     (ecb-source-in-directories-buffer-face ((t (:foreground "LightBlue1"))))
     (ecb-sources-face ((t (:foreground "LightBlue1"))))
     (ecb-sources-general-face ((t (:height 0.9))))
     (ecb-token-header-face ((t (:background "Steelblue4"))))
     (ecb-type-token-class-face ((t (:bold t :weight bold))))
     (ecb-type-token-enum-face ((t (:bold t :weight bold))))
     (ecb-type-token-group-face ((t (:bold t :foreground "dim gray" :weight bold))))
     (ecb-type-token-interface-face ((t (:bold t :weight bold))))
     (ecb-type-token-struct-face ((t (:bold t :weight bold))))
     (ecb-type-token-typedef-face ((t (:bold t :weight bold))))
     (ediff-current-diff-A ((t (:background "#000066"))))
     (ediff-current-diff-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-B ((t (:background "#666633"))))
     (ediff-current-diff-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-current-diff-face-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-face-Ancestor ((t (:background "VioletRed" :foreground "Gray30"))))
     (ediff-current-diff-face-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
     (ediff-current-diff-face-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-even-diff-A ((t (:background "gray30"))))
     (ediff-even-diff-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-B ((t (:background "Gray30"))))
     (ediff-even-diff-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-face-A ((t (:background "light grey" :foreground "Gray30"))))
     (ediff-even-diff-face-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-C ((t (:background "light grey" :foreground "Gray30"))))
     (ediff-fine-diff-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-B ((t (:background "#dddd66" :foreground "black"))))
     (ediff-fine-diff-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-fine-diff-face-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-face-Ancestor ((t (:background "Green" :foreground "Gray30"))))
     (ediff-fine-diff-face-B ((t (:background "cyan" :foreground "Gray30"))))
     (ediff-fine-diff-face-C ((t (:background "Turquoise" :foreground "Gray30"))))
     (ediff-odd-diff-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-Ancestor ((t (:background "gray40" :foreground "cyan3"))))
     (ediff-odd-diff-B ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-C ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-face-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-face-Ancestor ((t (:background "light grey" :foreground "Gray30"))))
     (ediff-odd-diff-face-B ((t (:background "light grey" :foreground "Gray30"))))
     (ediff-odd-diff-face-C ((t (:background "Grey" :foreground "White"))))
     (eev-glyph-face-Greek ((t (nil))))
     (eev-glyph-face-bang ((t (:background "red" :foreground "blue"))))
     (eev-glyph-face-blue ((t (:foreground "blue"))))
     (eev-glyph-face-bluebg ((t (:background "blue"))))
     (eev-glyph-face-font ((t (nil))))
     (eev-glyph-face-graphic ((t (nil))))
     (eev-glyph-face-greek ((t (nil))))
     (eev-glyph-face-green ((t (:bold t :foreground "yellow" :weight bold))))
     (eev-glyph-face-linear ((t (nil))))
     (eev-glyph-face-logical ((t (nil))))
     (eev-glyph-face-math ((t (nil))))
     (eev-glyph-face-red ((t (:bold t :background "red" :foreground "yellow" :weight bold))))
     (eev-glyph-face-yellow-on-red ((t (:background "red" :foreground "yellow"))))
     (emacs-wiki-bad-link-face ((t (:bold t :foreground "IndianRed1" :weight bold))))
     (emacs-wiki-header-1 ((t (:bold t :weight bold :height 1.728 :family "helv"))))
     (emacs-wiki-header-2 ((t (:bold t :weight bold :height 1.44 :family "helv"))))
     (emacs-wiki-header-3 ((t (:bold t :weight bold :height 1.2 :family "helv"))))
     (emacs-wiki-header-4 ((t (:bold t :weight bold :family "helv"))))
     (emacs-wiki-header-5 ((t (:bold t :weight bold))))
     (emacs-wiki-header-6 ((t (nil))))
     (emacs-wiki-link-face ((t (:bold t :foreground "khaki" :weight bold))))
     (emacs-wiki-verbatim-face ((t (:foreground "gray"))))
     (emms-pbi-current-face ((t (:bold t :foreground "gold2" :weight bold))))
     (emms-pbi-mark-marked-face ((t (:italic t :background "gray30" :foreground "slate gray" :slant italic))))
     (emms-pbi-song-face ((t (:foreground "gray60"))))
     (emms-stream-name-face ((t (nil))))
     (emms-stream-url-face ((t (nil))))
     (epa-field-body ((t (:italic t :slant italic))))
     (epa-field-name ((t (:bold t :weight bold))))
     (epa-mark ((t (:bold t :foreground "red" :weight bold))))
     (epa-string ((t (:foreground "blue4"))))
     (epa-validity-disabled ((t (:italic t :slant italic))))
     (epa-validity-high ((t (:bold t :weight bold))))
     (epa-validity-low ((t (:italic t :slant italic))))
     (epa-validity-medium ((t (:italic t :slant italic))))
     (erc-action-face ((t (:foreground "gray70"))))
     (erc-bold-face ((t (:bold t :weight bold))))
     (erc-chanlist-even-line-face ((t (nil))))
     (erc-chanlist-header-face ((t (nil))))
     (erc-chanlist-highlight ((t (nil))))
     (erc-chanlist-odd-line-face ((t (nil))))
     (erc-command-indicator-face ((t (:bold t :weight bold))))
     (erc-current-nick-face ((t (:bold t :foreground "orange1" :weight bold))))
     (erc-dangerous-host-face ((t (:foreground "red"))))
     (erc-default-face ((t (:foreground "gray60"))))
     (erc-direct-msg-face ((t (:foreground "pale green"))))
     (erc-error-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (erc-fool-face ((t (:foreground "Gray85"))))
     (erc-highlight-face ((t (:bold t :foreground "pale green" :weight bold))))
     (erc-input-face ((t (:foreground "gray90"))))
     (erc-inverse-face ((t (:background "steel blue"))))
     (erc-keyword-face ((t (nil))))
     (erc-nick-default-face ((t (:foreground "gold"))))
     (erc-nick-msg-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (erc-notice-face ((t (:foreground "gold"))))
     (erc-pal-face ((t (:foreground "cornflower blue"))))
     (erc-prompt-face ((t (:bold t :foreground "slate gray" :weight bold))))
     (erc-timestamp-face ((t (:foreground "slate gray"))))
     (erc-underline-face ((t (:underline t))))
     (escape-glyph ((t (:foreground "grey75"))))
     (eshell-ls-archive ((t (:bold t :foreground "Orchid" :weight bold))))
     (eshell-ls-archive-face ((t (:bold t :foreground "Orchid" :weight bold))))
     (eshell-ls-backup ((t (:foreground "LightSalmon"))))
     (eshell-ls-backup-face ((t (:foreground "LightSalmon"))))
     (eshell-ls-clutter ((t (:bold t :foreground "OrangeRed" :weight bold))))
     (eshell-ls-clutter-face ((t (:bold t :foreground "OrangeRed" :weight bold))))
     (eshell-ls-directory ((t (:bold t :foreground "SkyBlue" :weight bold))))
     (eshell-ls-directory-face ((t (:bold t :foreground "SkyBlue" :weight bold))))
     (eshell-ls-executable ((t (:bold t :foreground "Green" :weight bold))))
     (eshell-ls-executable-face ((t (:bold t :foreground "Green" :weight bold))))
     (eshell-ls-missing ((t (:bold t :foreground "Red" :weight bold))))
     (eshell-ls-missing-face ((t (:bold t :foreground "Red" :weight bold))))
     (eshell-ls-picture-face ((t (:foreground "violet"))))
     (eshell-ls-product ((t (:foreground "LightSalmon"))))
     (eshell-ls-product-face ((t (:foreground "LightSalmon"))))
     (eshell-ls-readonly ((t (:foreground "Pink"))))
     (eshell-ls-readonly-face ((t (:foreground "Pink"))))
     (eshell-ls-special ((t (:bold t :foreground "Magenta" :weight bold))))
     (eshell-ls-special-face ((t (:bold t :foreground "Magenta" :weight bold))))
     (eshell-ls-symlink ((t (:bold t :foreground "Cyan" :weight bold))))
     (eshell-ls-symlink-face ((t (:bold t :foreground "Cyan" :weight bold))))
     (eshell-ls-text-face ((t (nil))))
     (eshell-ls-todo-face ((t (nil))))
     (eshell-ls-unreadable ((t (:foreground "DarkGrey"))))
     (eshell-ls-unreadable-face ((t (:foreground "DarkGrey"))))
     (eshell-prompt ((t (:bold t :foreground "Pink" :weight bold))))
     (eshell-prompt-face ((t (:bold t :foreground "Pink" :weight bold))))
     (eshell-test-failed-face ((t (:bold t :weight bold))))
     (eshell-test-ok-face ((t (:bold t :weight bold))))
     (excerpt ((t (:italic t :slant italic))))
     (ff-paths-non-existant-file-face ((t (:bold t :foreground "gray85" :weight bold))))
     (fg:black ((t (:foreground "black"))))
     (fg:erc-color-face0 ((t (:foreground "white"))))
     (fg:erc-color-face1 ((t (:foreground "beige"))))
     (fg:erc-color-face10 ((t (:foreground "pale goldenrod"))))
     (fg:erc-color-face11 ((t (:foreground "light goldenrod yellow"))))
     (fg:erc-color-face12 ((t (:foreground "light yellow"))))
     (fg:erc-color-face13 ((t (:foreground "yellow"))))
     (fg:erc-color-face14 ((t (:foreground "light goldenrod"))))
     (fg:erc-color-face15 ((t (:foreground "lime green"))))
     (fg:erc-color-face2 ((t (:foreground "lemon chiffon"))))
     (fg:erc-color-face3 ((t (:foreground "light cyan"))))
     (fg:erc-color-face4 ((t (:foreground "powder blue"))))
     (fg:erc-color-face5 ((t (:foreground "sky blue"))))
     (fg:erc-color-face6 ((t (:foreground "dark sea green"))))
     (fg:erc-color-face7 ((t (:foreground "pale green"))))
     (fg:erc-color-face8 ((t (:foreground "medium spring green"))))
     (fg:erc-color-face9 ((t (:foreground "khaki"))))
     (file-name-shadow ((t (nil))))
     (fixed ((t (:bold t :weight bold))))
     (fixed-pitch ((t (:background "grey90"))))
     (fl-comment-face ((t (:foreground "gray85"))))
     (fl-doc-string-face ((t (nil))))
     (fl-function-name-face ((t (:foreground "green"))))
     (fl-keyword-face ((t (:foreground "LightGreen"))))
     (fl-string-face ((t (:foreground "light coral"))))
     (fl-type-face ((t (:foreground "cyan"))))
     (flyspell-duplicate ((t (:underline "Gold3"))))
     (flyspell-duplicate-face ((t (:underline "Gold3"))))
     (flyspell-incorrect ((t (:underline "OrangeRed"))))
     (flyspell-incorrect-face ((t (:underline "OrangeRed"))))
     (font-latex-bold-face ((t (nil))))
     (font-latex-doctex-documentation-face ((t (:background "#eeeeee"))))
     (font-latex-doctex-preprocessor-face ((t (:background "#eeeeee"))))
     (font-latex-italic-face ((t (nil))))
     (font-latex-math-face ((t (:background "gray90"))))
     (font-latex-sectioning-0-face ((t (:bold t :weight bold :foreground "blue4" :family "Optima" :height 1.6105100000000008))))
     (font-latex-sectioning-1-face ((t (:bold t :family "Optima" :foreground "blue4" :weight bold :height 1.4641000000000006))))
     (font-latex-sectioning-2-face ((t (:bold t :weight bold :foreground "blue4" :family "Optima" :height 1.3310000000000004))))
     (font-latex-sectioning-3-face ((t (:bold t :family "Optima" :foreground "blue4" :weight bold :height 1.2100000000000002))))
     (font-latex-sectioning-4-face ((t (:bold t :weight bold :foreground "blue4" :family "Optima" :height 1.1))))
     (font-latex-sectioning-5-face ((t (:bold t :family "Optima" :foreground "blue4" :weight bold))))
     (font-latex-sedate-face ((t (:underline t))))
     (font-latex-slide-title-face ((t (:bold t :family "Optima" :weight bold :height 1.2))))
     (font-latex-string-face ((t (:background "gray90"))))
     (font-latex-subscript-face ((t (:height 0.8))))
     (font-latex-superscript-face ((t (:height 0.8))))
     (font-latex-verbatim-face ((t (:foreground "tan4" :background "gray90"))))
     (font-latex-warning-face ((t (:foreground "gold"))))
     (font-lock-builtin-face ((t (:foreground "gray57"))))
     (font-lock-comment-delimiter-face ((t (:foreground "gray40"))))
     (font-lock-comment-face ((t (:foreground "gray40"))))
     (font-lock-constant-face ((t (:foreground "#5f9900"))))
     (font-lock-doc-face ((t (:foreground "gray30" :background "#d7d3bc"))))
     (font-lock-doc-string-face ((t (:foreground "gray30" :background "#d7d3bc"))))
     (font-lock-exit-face ((t (:foreground "red"))))
     (font-lock-function-name-face ((t (;; :background "#d5dee4"
					:foreground "RoyalBlue4"))))
     (font-lock-interface-def-face ((t (nil))))
     (font-lock-keyword-face ((t (:bold t :weight bold :foreground "black"))))
     (font-lock-module-def-face ((t (nil))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-other-emphasized-face ((t (nil))))
     (font-lock-other-type-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:inherit font-lock-keyword-face))))
     (font-lock-reference-face ((t (:background "red" :foreground "yellow"))))
     (font-lock-regexp-grouping-backslash ((t (:foreground "gray60"))))
     (font-lock-regexp-grouping-construct ((t (:foreground "black"))))
     (font-lock-string-face ((t (:background "#d0ccb5" :foreground "tan4"))))
;;      (font-lock-string-face ((t (:background "gray90" :foreground "tan4"))))
     (font-lock-type-def-face ((t (nil))))
     (font-lock-type-face ((t (:foreground "#bc0000"))))
     (font-lock-variable-name-face ((t (:foreground "#985321"))))
     (font-lock-warning-face ((t (:background "orange"))))
     (fringe ((t (:background "#d5d1ba"))))
     (gamegrid-face-*Tetris* ((t (:stipple nil :background "gray20" :foreground "gray70" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 0.8421052631578947 :width normal :family "apple-inconsolata"))))
     (gnus-cite-1 ((t (:foreground "light blue"))))
     (gnus-cite-10 ((t (:foreground "medium purple"))))
     (gnus-cite-11 ((t (:foreground "turquoise"))))
     (gnus-cite-2 ((t (:foreground "light cyan"))))
     (gnus-cite-3 ((t (:foreground "light yellow"))))
     (gnus-cite-4 ((t (:foreground "light pink"))))
     (gnus-cite-5 ((t (:foreground "pale green"))))
     (gnus-cite-6 ((t (:foreground "beige"))))
     (gnus-cite-7 ((t (:foreground "orange"))))
     (gnus-cite-8 ((t (:foreground "magenta"))))
     (gnus-cite-9 ((t (:foreground "violet"))))
     (gnus-cite-attribution ((t (:italic t :slant italic))))
     (gnus-cite-attribution-face ((t (:italic t :slant italic))))
     (gnus-cite-face-1 ((t (:foreground "light blue"))))
     (gnus-cite-face-10 ((t (:foreground "medium purple"))))
     (gnus-cite-face-11 ((t (:foreground "turquoise"))))
     (gnus-cite-face-2 ((t (:foreground "light cyan"))))
     (gnus-cite-face-3 ((t (:foreground "light yellow"))))
     (gnus-cite-face-4 ((t (:foreground "light pink"))))
     (gnus-cite-face-5 ((t (:foreground "pale green"))))
     (gnus-cite-face-6 ((t (:foreground "beige"))))
     (gnus-cite-face-7 ((t (:foreground "orange"))))
     (gnus-cite-face-8 ((t (:foreground "magenta"))))
     (gnus-cite-face-9 ((t (:foreground "violet"))))
     (gnus-emphasis-bold ((t (:bold t :weight bold))))
     (gnus-emphasis-bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (gnus-emphasis-highlight-words ((t (:background "black" :foreground "yellow"))))
     (gnus-emphasis-italic ((t (:italic t :slant italic))))
     (gnus-emphasis-strikethru ((t (nil))))
     (gnus-emphasis-underline ((t (:underline t))))
     (gnus-emphasis-underline-bold ((t (:bold t :underline t :weight bold))))
     (gnus-emphasis-underline-bold-italic ((t (:italic t :bold t :underline t :slant italic :weight bold))))
     (gnus-emphasis-underline-italic ((t (:italic t :underline t :slant italic))))
     (gnus-filterhist-face-1 ((t (nil))))
     (gnus-group-mail-1 ((t (:bold t :foreground "aquamarine1" :weight bold))))
     (gnus-group-mail-1-empty ((t (:foreground "aquamarine1"))))
     (gnus-group-mail-1-empty-face ((t (:foreground "aquamarine1"))))
     (gnus-group-mail-1-face ((t (:bold t :foreground "aquamarine1" :weight bold))))
     (gnus-group-mail-2 ((t (:bold t :foreground "aquamarine2" :weight bold))))
     (gnus-group-mail-2-empty ((t (:foreground "aquamarine2"))))
     (gnus-group-mail-2-empty-face ((t (:foreground "aquamarine2"))))
     (gnus-group-mail-2-face ((t (:bold t :foreground "aquamarine2" :weight bold))))
     (gnus-group-mail-3 ((t (:bold t :foreground "aquamarine3" :weight bold))))
     (gnus-group-mail-3-empty ((t (:foreground "aquamarine3"))))
     (gnus-group-mail-3-empty-face ((t (:foreground "aquamarine3"))))
     (gnus-group-mail-3-face ((t (:bold t :foreground "aquamarine3" :weight bold))))
     (gnus-group-mail-low ((t (:bold t :foreground "aquamarine4" :weight bold))))
     (gnus-group-mail-low-empty ((t (:foreground "aquamarine4"))))
     (gnus-group-mail-low-empty-face ((t (:foreground "aquamarine4"))))
     (gnus-group-mail-low-face ((t (:bold t :foreground "aquamarine4" :weight bold))))
     (gnus-group-news-1 ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (gnus-group-news-1-empty ((t (:foreground "PaleTurquoise"))))
     (gnus-group-news-1-empty-face ((t (:foreground "PaleTurquoise"))))
     (gnus-group-news-1-face ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (gnus-group-news-2 ((t (:bold t :foreground "turquoise" :weight bold))))
     (gnus-group-news-2-empty ((t (:foreground "turquoise"))))
     (gnus-group-news-2-empty-face ((t (:foreground "turquoise"))))
     (gnus-group-news-2-face ((t (:bold t :foreground "turquoise" :weight bold))))
     (gnus-group-news-3 ((t (:bold t :weight bold))))
     (gnus-group-news-3-empty ((t (nil))))
     (gnus-group-news-3-empty-face ((t (nil))))
     (gnus-group-news-3-face ((t (:bold t :weight bold))))
     (gnus-group-news-4 ((t (:bold t :weight bold))))
     (gnus-group-news-4-empty ((t (nil))))
     (gnus-group-news-4-empty-face ((t (nil))))
     (gnus-group-news-4-face ((t (:bold t :weight bold))))
     (gnus-group-news-5 ((t (:bold t :weight bold))))
     (gnus-group-news-5-empty ((t (nil))))
     (gnus-group-news-5-empty-face ((t (nil))))
     (gnus-group-news-5-face ((t (:bold t :weight bold))))
     (gnus-group-news-6 ((t (:bold t :weight bold))))
     (gnus-group-news-6-empty ((t (nil))))
     (gnus-group-news-6-empty-face ((t (nil))))
     (gnus-group-news-6-face ((t (:bold t :weight bold))))
     (gnus-group-news-low ((t (:bold t :foreground "DarkTurquoise" :weight bold))))
     (gnus-group-news-low-empty ((t (:foreground "DarkTurquoise"))))
     (gnus-group-news-low-empty-face ((t (:foreground "DarkTurquoise"))))
     (gnus-group-news-low-face ((t (:bold t :foreground "DarkTurquoise" :weight bold))))
     (gnus-header-content ((t (:italic t :foreground "forest green" :slant italic))))
     (gnus-header-content-face ((t (:italic t :foreground "forest green" :slant italic))))
     (gnus-header-from ((t (:foreground "spring green"))))
     (gnus-header-from-face ((t (:foreground "spring green"))))
     (gnus-header-name ((t (:foreground "SeaGreen"))))
     (gnus-header-name-face ((t (:foreground "SeaGreen"))))
     (gnus-header-newsgroups ((t (:italic t :foreground "yellow" :slant italic))))
     (gnus-header-newsgroups-face ((t (:italic t :foreground "yellow" :slant italic))))
     (gnus-header-subject ((t (:foreground "SeaGreen3"))))
     (gnus-header-subject-face ((t (:foreground "SeaGreen3"))))
     (gnus-picon-face ((t (:background "white" :foreground "black"))))
     (gnus-picon-xbm-face ((t (:background "white" :foreground "black"))))
     (gnus-picons-face ((t (:background "white" :foreground "gray30"))))
     (gnus-picons-xbm-face ((t (:background "white" :foreground "gray30"))))
     (gnus-server-agent ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (gnus-server-agent-face ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (gnus-server-closed ((t (:italic t :foreground "Light Steel Blue" :slant italic))))
     (gnus-server-closed-face ((t (:italic t :foreground "Light Steel Blue" :slant italic))))
     (gnus-server-denied ((t (:bold t :foreground "Pink" :weight bold))))
     (gnus-server-denied-face ((t (:bold t :foreground "Pink" :weight bold))))
     (gnus-server-offline ((t (:bold t :foreground "Yellow" :weight bold))))
     (gnus-server-offline-face ((t (:bold t :foreground "Yellow" :weight bold))))
     (gnus-server-opened ((t (:bold t :foreground "Green1" :weight bold))))
     (gnus-server-opened-face ((t (:bold t :foreground "Green1" :weight bold))))
     (gnus-signature ((t (:italic t :slant italic))))
     (gnus-signature-face ((t (:italic t :slant italic))))
     (gnus-splash ((t (:foreground "Brown"))))
     (gnus-splash-face ((t (:foreground "Brown"))))
     (gnus-summary-cancelled ((t (:background "black" :foreground "yellow"))))
     (gnus-summary-cancelled-face ((t (:background "black" :foreground "yellow"))))
     (gnus-summary-high-ancient ((t (:bold t :foreground "SkyBlue" :weight bold))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "SkyBlue" :weight bold))))
     (gnus-summary-high-read ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (gnus-summary-high-ticked ((t (:bold t :foreground "pink" :weight bold))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "pink" :weight bold))))
     (gnus-summary-high-undownloaded ((t (:bold t :foreground "LightGray" :weight bold))))
     (gnus-summary-high-undownloaded-face ((t (:bold t :foreground "LightGray" :weight bold))))
     (gnus-summary-high-unread ((t (:bold t :weight bold))))
     (gnus-summary-high-unread-face ((t (:bold t :weight bold))))
     (gnus-summary-low-ancient ((t (:italic t :foreground "SkyBlue" :slant italic))))
     (gnus-summary-low-ancient-face ((t (:italic t :foreground "SkyBlue" :slant italic))))
     (gnus-summary-low-read ((t (:italic t :foreground "PaleGreen" :slant italic))))
     (gnus-summary-low-read-face ((t (:italic t :foreground "PaleGreen" :slant italic))))
     (gnus-summary-low-ticked ((t (:italic t :foreground "pink" :slant italic))))
     (gnus-summary-low-ticked-face ((t (:italic t :foreground "pink" :slant italic))))
     (gnus-summary-low-undownloaded ((t (:italic t :foreground "LightGray" :slant italic :weight normal))))
     (gnus-summary-low-undownloaded-face ((t (:italic t :foreground "LightGray" :slant italic :weight normal))))
     (gnus-summary-low-unread ((t (:italic t :slant italic))))
     (gnus-summary-low-unread-face ((t (:italic t :slant italic))))
     (gnus-summary-normal-ancient ((t (:foreground "SkyBlue"))))
     (gnus-summary-normal-ancient-face ((t (:foreground "SkyBlue"))))
     (gnus-summary-normal-read ((t (:foreground "PaleGreen"))))
     (gnus-summary-normal-read-face ((t (:foreground "PaleGreen"))))
     (gnus-summary-normal-ticked ((t (:foreground "pink"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "pink"))))
     (gnus-summary-normal-undownloaded ((t (:foreground "LightGray" :weight normal))))
     (gnus-summary-normal-undownloaded-face ((t (:foreground "LightGray" :weight normal))))
     (gnus-summary-normal-unread ((t (nil))))
     (gnus-summary-normal-unread-face ((t (nil))))
     (gnus-summary-selected ((t (:underline t))))
     (gnus-summary-selected-face ((t (:underline t))))
     (gnus-x-face ((t (:background "white" :foreground "gray30"))))
     (golisp-anchor-face ((t (:bold t :foreground "yellow" :weight bold))))
     (golisp-bullet-face ((t (:foreground "yellow"))))
     (golisp-defxref-name-face ((t (:bold t :foreground "gray60" :weight bold))))
     (golisp-xref-face ((t (:bold t :foreground "yellow" :weight bold))))
     (green ((t (:foreground "green"))))
     (gui-button-face ((t (:background "grey75" :foreground "gray30"))))
     (gui-element ((t (:background "Gray80"))))
     (header-line ((t (:background "Grey90"))))
     (help-argument-name ((t (:italic t :slant italic))))
     (help-highlight-face ((t (:bold t :underline t :weight bold))))
     (hexl-address-area ((t (nil))))
     (hexl-address-region ((t (nil))))
     (hexl-ascii-area ((t (nil))))
     (hexl-ascii-region ((t (nil))))
     (hi-black-b ((t (:bold t :weight bold))))
     (hi-black-hb ((t (:bold t :weight bold :height 1.67 :family "helv"))))
     (hi-blue ((t (:background "lightblue4"))))
     (hi-blue-b ((t (:bold t :foreground "blue" :weight bold))))
     (hi-green ((t (:background "green"))))
     (hi-green-b ((t (:bold t :foreground "green" :weight bold))))
     (hi-pink ((t (:background "pink"))))
     (hi-red-b ((t (:bold t :foreground "red" :weight bold))))
     (hi-yellow ((t (:background "yellow"))))
     (highlight ((t (:background "slateblue4" :foreground "lightsteelblue1"))))
     (highlight-changes ((t (:background "gray16"))))
     (highlight-changes-1 ((t (:foreground "yellow"))))
     (highlight-changes-2 ((t (:foreground "magenta"))))
     (highlight-changes-3 ((t (:foreground "blue"))))
     (highlight-changes-4 ((t (:foreground "maroon"))))
     (highlight-changes-5 ((t (:foreground "firebrick"))))
     (highlight-changes-6 ((t (:foreground "green4"))))
     (highlight-changes-7 ((t (:foreground "DarkOrchid"))))
     (highlight-changes-delete ((t (:background "#332222" :foreground "gray85"))))
     (highlight-changes-delete-face ((t (:background "#332222" :foreground "gray85"))))
     (highlight-changes-face ((t (:background "gray16"))))
     (highline-face ((t (:background "DeepSkyBlue4"))))
     (highline-vertical-face ((t (:background "lightcyan"))))
     (hl-line ((t (:background "#ffe"))))
     (holiday ((t (:background "chocolate4"))))
     (howm-menu-key-face ((t (:foreground "orange"))))
     (howm-menu-list-face ((t (:foreground "white"))))
     (howm-mode-keyword-face ((t (:bold t :background "dodgerblue2" :foreground "white" :weight bold))))
     (howm-mode-ref-face ((t (:bold t :background "ForestGreen" :foreground "yellow" :weight bold))))
     (howm-mode-title-face ((t (:bold t :background "DodgerBlue3" :foreground "white" :weight bold))))
     (howm-mode-wiki-face ((t (:foreground "cyan"))))
     (howm-reminder-deadline-face ((t (:background "red" :foreground "yellow"))))
     (howm-reminder-defer-face ((t (:background "violetred4" :foreground "magenta"))))
     (howm-reminder-done-face ((t (:background "gray40" :foreground "gray90"))))
     (howm-reminder-normal-face ((t (:background "forestgreen" :foreground "yellow"))))
     (howm-reminder-schedule-face ((t (:background "darkorange2" :foreground "yellow"))))
     (howm-reminder-separator-face ((t (:foreground "black"))))
     (howm-reminder-today-face ((t (:underline "yellow"))))
     (howm-reminder-todo-face ((t (:background "dodgerblue3" :foreground "cyan"))))
     (howm-reminder-tomorrow-face ((t (:italic t :slant italic))))
     (howm-view-empty-face ((t (nil))))
     (howm-view-hilit-face ((t (:bold t :background "forestgreen" :foreground "yellow" :weight bold))))
     (howm-view-name-face ((t (nil))))
     (html-helper-bold-face ((t (:bold t :weight bold))))
     (html-helper-bold-italic-face ((t (nil))))
     (html-helper-builtin-face ((t (:foreground "gray85" :underline t))))
     (html-helper-italic-face ((t (:bold t :foreground "yellow" :weight bold))))
     (html-helper-underline-face ((t (:underline t))))
     (html-tag-face ((t (:bold t :weight bold))))
     (hyper-apropos-documentation ((t (nil))))
     (hyper-apropos-heading ((t (:bold t :weight bold))))
     (hyper-apropos-hyperlink ((t (nil))))
     (hyper-apropos-major-heading ((t (:bold t :weight bold))))
     (hyper-apropos-section-heading ((t (:bold t :weight bold))))
     (hyper-apropos-warning ((t (:bold t :foreground "gray85" :weight bold))))
     (ibuffer-marked-face ((t (:foreground "gray85"))))
     (idlwave-help-link-face ((t (:foreground "Blue"))))
     (idlwave-shell-bp-face ((t (:background "Pink" :foreground "Black"))))
     (ido-first-match ((t (:underline t))))
     (ido-first-match-face ((t (nil))))
     (ido-incomplete-regexp ((t (:underline "red"))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-indicator-face ((t (nil))))
     (ido-only-match ((t (:background "YellowGreen" :underline t))))
     (ido-only-match-face ((t (nil))))
     (ido-subdir ((t (:foreground "red1"))))
     (ido-subdir-face ((t (nil))))
     (info-header-node ((t (:bold t :weight bold))))
     (info-header-xref ((t (:bold t :foreground "sky blue" :weight bold))))
     (info-menu-5 ((t (:foreground "red1"))))
     (info-menu-6 ((t (nil))))
     (info-menu-header ((t (:bold t :weight bold :family "helv"))))
     (info-menu-star ((t (:foreground "red1"))))
     (info-node ((t (:bold t :weight bold))))
     (info-title-1 ((t (:bold t :weight bold :height 1.728 :family "helv"))))
     (info-title-2 ((t (:bold t :weight bold :height 1.44 :family "helv"))))
     (info-title-3 ((t (:bold t :weight bold :height 1.2 :family "helv"))))
     (info-title-4 ((t (:bold t :weight bold :family "helv"))))
     (info-xref ((t (:bold t :foreground "sky blue" :weight bold))))
     (info-xref-visited ((t (:bold t :foreground "magenta3" :weight bold))))
     (isearch ((t (:background "LightSlateBlue"))))
     (isearch-secondary ((t (:foreground "red3"))))
     (iswitchb-current-match ((t (nil))))
     (iswitchb-invalid-regexp ((t (nil))))
     (iswitchb-single-match ((t (nil))))
     (iswitchb-virtual-matches ((t (nil))))
     (italic ((t (:italic t :slant italic))))
     (jde-bug-breakpoint-cursor ((t (:background "brown" :foreground "cyan"))))
     (jde-bug-breakpoint-marker ((t (:background "yellow" :foreground "red"))))
     (jde-java-font-lock-api-face ((t (:foreground "light goldenrod"))))
     (jde-java-font-lock-bold-face ((t (:bold t :weight bold))))
     (jde-java-font-lock-code-face ((t (nil))))
     (jde-java-font-lock-constant-face ((t (:foreground "Aquamarine"))))
     (jde-java-font-lock-doc-tag-face ((t (:foreground "light coral"))))
     (jde-java-font-lock-italic-face ((t (:italic t :slant italic))))
     (jde-java-font-lock-link-face ((t (:foreground "blue" :underline t :slant normal))))
     (jde-java-font-lock-modifier-face ((t (:foreground "LightSteelBlue"))))
     (jde-java-font-lock-number-face ((t (:foreground "LightSalmon"))))
     (jde-java-font-lock-operator-face ((t (:foreground "cyan3"))))
     (jde-java-font-lock-package-face ((t (:foreground "steelblue1"))))
     (jde-java-font-lock-pre-face ((t (nil))))
     (jde-java-font-lock-underline-face ((t (:underline t))))
     (lazy-highlight ((t (:background "gray80"))))
     (lazy-highlight-face ((t (:bold t :foreground "yellow" :weight bold))))
     (left-margin ((t (nil))))
     (linemenu-face ((t (:background "gray30"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:foreground "violet" :underline t))))
     (linkd-command-face ((t (:background "goldenrod4" :foreground "gold"))))
     (linkd-generic-face ((t (:foreground "aquamarine1"))))
     (linkd-generic-name-face ((t (:background "aquamarine4" :foreground "aquamarine1" :underline "yellow"))))
     (linkd-icon-face ((t (:underline nil))))
     (linkd-star-face ((t (:background "red" :foreground "yellow" :underline nil))))
     (linkd-star-name-face ((t (:background "olivedrab4" :foreground "yellow" :underline "yellow"))))
     (linkd-tag-face ((t (:background "palevioletred3" :foreground "yellow" :underline nil))))
     (linkd-tag-name-face ((t (:background "aquamarine4" :foreground "aquamarine1" :underline "yellow"))))
     (linkd-wiki-face ((t (:foreground "cyan" :underline "yellow"))))
     (list-mode-item-selected ((t (:background "gray68"))))
     (log-view-file-face ((t (:bold t :background "grey70" :weight bold))))
     (log-view-message-face ((t (nil))))
     (mac-ts-block-fill-text ((t (:underline t))))
     (mac-ts-caret-position ((t (nil))))
     (mac-ts-converted-text ((t (:underline "gray20"))))
     (mac-ts-no-hilite ((t (:background "gray20" :foreground "gray70" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 141 :width normal :family "apple-inconsolata"))))
     (mac-ts-outline-text ((t (:underline t))))
     (mac-ts-raw-text ((t (:underline t))))
     (mac-ts-selected-converted-text ((t (:underline t))))
     (mac-ts-selected-raw-text ((t (:underline t))))
     (mac-ts-selected-text ((t (:underline t))))
     (magenta ((t (:foreground "gray85"))))
     (makefile-makepp-perl ((t (:background "DarkBlue"))))
     (makefile-shell ((t (nil))))
     (makefile-space ((t (:background "hotpink"))))
     (makefile-space-face ((t (:background "hotpink"))))
     (makefile-targets ((t (:foreground "RoyalBlue4" :background "lightsteelblue1"))))
     (man-bold ((t (:bold t :weight bold))))
     (man-heading ((t (:bold t :weight bold))))
     (man-italic ((t (:foreground "yellow"))))
     (man-xref ((t (:underline t))))
     (markdown-blockquote-face ((t (:background "grey92" :foreground "gray40"))))
     (markdown-bold-face ((t (:bold t :foreground "sienna" :weight bold))))
     (markdown-comment-face ((t (:foreground "gray40"))))
     (markdown-header-face ((t (:bold t :foreground "RoyalBlue4" :background "lightsteelblue1" :weight bold))))
     (markdown-header-face-1 ((t (:bold t :weight bold :background "lightsteelblue1" :foreground "RoyalBlue4"))))
     (markdown-header-face-2 ((t (:bold t :weight bold :background "lightsteelblue1" :foreground "RoyalBlue4"))))
     (markdown-header-face-3 ((t (:bold t :weight bold :background "lightsteelblue1" :foreground "RoyalBlue4"))))
     (markdown-header-face-4 ((t (:bold t :weight bold :background "lightsteelblue1" :foreground "RoyalBlue4"))))
     (markdown-header-face-5 ((t (:bold t :weight bold :background "lightsteelblue1" :foreground "RoyalBlue4"))))
     (markdown-header-face-6 ((t (:bold t :weight bold :background "lightsteelblue1" :foreground "RoyalBlue4"))))
     (markdown-inline-code-face ((t (:foreground "#5f9900"))))
     (markdown-italic-face ((t (:italic t :foreground "sienna" :slant italic))))
     (markdown-link-face ((t (:bold t :weight bold))))
     (markdown-link-title-face ((t (:foreground "gray40"))))
     (markdown-list-face ((t (:foreground "gray57"))))
     (markdown-math-face ((t (:foreground "tan4" :background "gray90"))))
     (markdown-pre-face ((t (nil))))
     (markdown-reference-face ((t (:foreground "red3"))))
     (markdown-url-face ((t (:foreground "tan4" :background "gray90"))))
     (match ((t (:background "LightSteelBlue1"))))
     (menu ((t (:background "MidnightBlue" :foreground "Grey"))))
     (message-cited-text ((t (:foreground "orange"))))
     (message-header-cc ((t (:foreground "khaki"))))
     (message-header-contents ((t (:foreground "white"))))
     (message-header-name ((t (:foreground "LightBlue"))))
     (message-header-newsgroups ((t (:italic t :bold t :foreground "MediumAquamarine" :slant italic :weight bold))))
     (message-header-other ((t (:foreground "MediumAquamarine"))))
     (message-header-subject ((t (:bold t :foreground "light cyan" :weight bold))))
     (message-header-to ((t (:bold t :foreground "light cyan" :weight bold))))
     (message-header-xheader ((t (:foreground "MediumAquamarine"))))
     (message-headers ((t (:bold t :foreground "orange" :weight bold))))
     (message-highlighted-header-contents ((t (:bold t :weight bold))))
     (message-mml ((t (:foreground "ForestGreen"))))
     (message-separator ((t (:foreground "chocolate"))))
     (message-url ((t (:bold t :foreground "pink" :weight bold))))
     (minibuffer-prompt ((t (:bold t :background "red" :foreground "yellow" :weight bold))))
     (mmm-default-submode-face ((t (:background "#c0c0c5"))))
     (mmm-face ((t (:background "black" :foreground "green"))))
     (mode-line ((t (:background "#dff" :foreground "black" :box (:line-width -1 :color "gray40")))))
     (mode-line-buffer-id ((t (:foreground "red3"))))
     (mode-line-highlight ((t (nil))))
     (mode-line-inactive ((t (:background "gray95" :foreground "gray60" :box (:line-width -1 :color "grey60")))))
     (modeline-mousable ((t (nil))))
     (modeline-mousable-minor-mode ((t (nil))))
     (mouse ((t (:background "Grey"))))
     (my-summary-highlight-face ((t (:background "PaleTurquoise4" :foreground "White"))))
     (my-tab-face ((t (nil))))
     (my-url-face ((t (:foreground "LightBlue"))))
     (next-error ((t (:background "grey30"))))
     (nil ((t (nil))))
     (nobreak-space ((t (nil))))
     (nxml-attribute-colon-face ((t (:foreground "#ACACFC"))))
     (nxml-attribute-local-name-face ((t (:foreground "#ACACFC"))))
     (nxml-attribute-prefix-face ((t (:foreground "#ACACFC"))))
     (nxml-attribute-value-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-attribute-value-face ((t (:foreground "#70F170"))))
     (nxml-cdata-section-CDATA-face ((t (:foreground "#ACACFC"))))
     (nxml-cdata-section-content-face ((t (nil))))
     (nxml-cdata-section-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-char-ref-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-char-ref-number-face ((t (:foreground "#00AD00"))))
     (nxml-comment-content-face ((t (:italic t :slant italic))))
     (nxml-comment-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-delimited-data-face ((t (:foreground "#70F170"))))
     (nxml-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-element-colon-face ((t (:foreground "#ACACFC"))))
     (nxml-element-local-name-face ((t (:foreground "#ACACFC"))))
     (nxml-element-prefix-face ((t (:foreground "#ACACFC"))))
     (nxml-entity-ref-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-entity-ref-name-face ((t (:foreground "#00AD00"))))
     (nxml-glyph-face ((t (:background "light grey" :foreground "black" :slant normal :weight normal))))
     (nxml-hash-face ((t (:foreground "#ACACFC"))))
     (nxml-heading-face ((t (:bold t :weight bold))))
     (nxml-markup-declaration-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-name-face ((t (:foreground "#ACACFC"))))
     (nxml-namespace-attribute-colon-face ((t (:foreground "#ACACFC"))))
     (nxml-namespace-attribute-prefix-face ((t (:foreground "#ACACFC"))))
     (nxml-namespace-attribute-value-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-namespace-attribute-value-face ((t (:foreground "#70F170"))))
     (nxml-namespace-attribute-xmlns-face ((t (:foreground "#ACACFC"))))
     (nxml-outline-active-indicator-face ((t (:background "gray20" :foreground "gray70" :inverse-video nil :box 1 :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 141 :width normal :family "apple-inconsolata"))))
     (nxml-outline-ellipsis-face ((t (:bold t :background "gray20" :foreground "gray70" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight bold :height 141 :width normal :family "apple-inconsolata"))))
     (nxml-outline-indicator-face ((t (:background "gray20" :foreground "gray70" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 141 :width normal :family "apple-inconsolata"))))
     (nxml-processing-instruction-content-face ((t (:foreground "#70F170"))))
     (nxml-processing-instruction-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-processing-instruction-target-face ((t (:foreground "#ACACFC"))))
     (nxml-prolog-keyword-face ((t (:foreground "#ACACFC"))))
     (nxml-prolog-literal-content-face ((t (:foreground "#70F170"))))
     (nxml-prolog-literal-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-ref-face ((t (:foreground "#00AD00"))))
     (nxml-tag-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-tag-slash-face ((t (:foreground "#ACACFC"))))
     (nxml-text-face ((t (nil))))
     (org-agenda-restriction-lock ((t (:background "yellow1"))))
     (org-agenda-structure ((t (:foreground "Blue1"))))
     (org-archived ((t (:foreground "grey70"))))
     (org-code ((t (:foreground "slategray"))))
     (org-column ((t (:background "grey30" :height 171 :family "apple-inconsolata"))))
     (org-date ((t (:foreground "cyan" :underline t))))
     (org-deadline-announce ((t (:foreground "red"))))
     (org-done ((t (:bold t :foreground "yellowgreen" :weight bold))))
     (org-drawer ((t (:foreground "Blue1"))))
     (org-ellipsis ((t (:foreground "DarkGoldenrod" :underline t))))
     (org-formula ((t (:foreground "chocolate1"))))
     (org-headline-done ((t (:foreground "palegreen"))))
     (org-hide ((t (:foreground "black"))))
     (org-latex-and-export-specials ((t (:foreground "SaddleBrown"))))
     (org-level-1 ((t (:foreground "RoyalBlue4"))))
     (org-level-2 ((t (:foreground "RoyalBlue3"))))
     (org-level-3 ((t (:foreground "RoyalBlue3"))))
     (org-level-4 ((t (:foreground "lightgoldenrod"))))
     (org-level-5 ((t (:foreground "darkkhaki"))))
     (org-level-6 ((t (:foreground "Aquamarine"))))
     (org-level-7 ((t (:foreground "LightSteelBlue"))))
     (org-level-8 ((t (:foreground "LightSalmon"))))
     (org-link ((t (:foreground "RoyalBlue4" :underline t))))
     (org-property-value ((t (nil))))
     (org-scheduled-previously ((t (:foreground "red"))))
     (org-scheduled-today ((t (:foreground "LightSkyBlue"))))
     (org-sexp-date ((t (:foreground "Purple"))))
     (org-special-keyword ((t (:foreground "cyan"))))
     (org-table ((t (:foreground "LightSkyBlue"))))
     (org-tag ((t (:bold t :weight bold))))
     (org-target ((t (:underline t))))
     (org-time-grid ((t (:foreground "LightGoldenrod"))))
     (org-todo ((t (:bold t :foreground "orangered" :weight bold))))
     (org-upcoming-deadline ((t (nil))))
     (org-verbatim ((t (:foreground "grey50" :underline t))))
     (org-warning ((t (:bold t :foreground "Red1" :weight bold))))
     (outline-1 ((t (:italic t :bold t :foreground "LightSkyBlue" :slant italic :weight bold))))
     (outline-2 ((t (:italic t :bold t :foreground "LightGoldenrod" :slant italic :weight bold))))
     (outline-3 ((t (:bold t :foreground "Cyan" :weight bold))))
     (outline-4 ((t (:bold t :foreground "LightSteelBlue" :weight bold))))
     (outline-5 ((t (:italic t :foreground "medium aquamarine" :slant italic))))
     (outline-6 ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (outline-7 ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (outline-8 ((t (:italic t :foreground "aquamarine" :slant italic))))
     (p4-depot-added-face ((t (nil))))
     (p4-depot-deleted-face ((t (nil))))
     (p4-depot-unmapped-face ((t (nil))))
     (p4-diff-change-face ((t (nil))))
     (p4-diff-del-face ((t (nil))))
     (p4-diff-file-face ((t (nil))))
     (p4-diff-head-face ((t (nil))))
     (p4-diff-ins-face ((t (nil))))
     (paren-blink-off ((t (:foreground "gray80"))))
     (paren-dim-face ((t (nil))))
     (paren-face ((t (nil))))
     (paren-face-match ((t (:background "slateblue"))))
     (paren-face-mismatch ((t (:background "purple" :foreground "white"))))
     (paren-face-no-match ((t (:background "yellow" :foreground "gray30"))))
     (paren-match ((t (:background "darkseagreen2"))))
     (paren-mismatch ((t (:background "RosyBrown" :foreground "gray30"))))
     (paren-mismatch-face ((t (:bold t :background "white" :foreground "red" :weight bold))))
     (paren-no-match-face ((t (:bold t :background "white" :foreground "red" :weight bold))))
     (planner-cancelled-task-face ((t (:foreground "gray" :strike-through t))))
     (planner-completed-task-face ((t (:foreground "gray" :strike-through t))))
     (planner-delegated-task-face ((t (:italic t :slant italic))))
     (planner-high-priority-task-face ((t (:foreground "red"))))
     (planner-id-face ((t (:foreground "darkgray"))))
     (planner-in-progress-task-face ((t (:bold t :weight bold))))
     (planner-low-priority-task-face ((t (:foreground "blue"))))
     (planner-medium-priority-task-face ((t (:foreground "green"))))
     (planner-note-headline-face ((t (:bold t :foreground "dark slate blue" :weight bold))))
     (pointer ((t (nil))))
     (preview-face ((t (:background "beige"))))
     (preview-reference-face ((t (nil))))
     (primary-selection ((t (:background "gray40"))))
     (qt-classes-face ((t (nil))))
     (query-replace ((t (:background "LightSlateBlue"))))
     (rcirc-bright-nick ((t (:foreground "Aquamarine"))))
     (rcirc-dim-nick ((t (:background "saddlebrown" :foreground "orange" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98))))
     (rcirc-keyword ((t (nil))))
     (rcirc-mode-line-nick ((t (:bold t :weight bold))))
     (rcirc-my-nick ((t (:foreground "gold"))))
     (rcirc-my-nick-face ((t (:bold t :foreground "gold" :weight bold))))
     (rcirc-nick-in-message ((t (:foreground "gold"))))
     (rcirc-nick-in-message-face ((t (:foreground "greenyellow"))))
     (rcirc-nick-in-message-full-line ((t (:foreground "gold"))))
     (rcirc-other-nick ((t (:foreground "gray60"))))
     (rcirc-other-nick-face ((t (:bold t :foreground "lightskyblue" :weight bold))))
     (rcirc-prompt ((t (:foreground "gray50"))))
     (rcirc-server ((t (:foreground "gray50"))))
     (rcirc-server-face ((t (nil))))
     (rcirc-server-prefix ((t (:foreground "gray60"))))
     (rcirc-timestamp ((t (:foreground "gray"))))
     (rcirc-track-keyword ((t (nil))))
     (rcirc-track-nick ((t (nil))))
     (rcirc-url ((t (nil))))
     (reb-match-0 ((t (:background "lightblue"))))
     (reb-match-1 ((t (:background "aquamarine"))))
     (reb-match-2 ((t (:background "springgreen"))))
     (reb-match-3 ((t (:background "yellow"))))
     (red ((t (:foreground "red"))))
     (region ((t (:inverse-video t))))
     (right-margin ((t (nil))))
     (rng-error-face ((t (:underline "red"))))
     (rpm-spec-dir-face ((t (nil))))
     (rpm-spec-doc-face ((t (nil))))
     (rpm-spec-ghost-face ((t (nil))))
     (rpm-spec-macro-face ((t (nil))))
     (rpm-spec-package-face ((t (nil))))
     (rpm-spec-tag-face ((t (nil))))
     (ruler-mode-column-number-face ((t (nil))))
     (ruler-mode-comment-column-face ((t (nil))))
     (ruler-mode-current-column-face ((t (nil))))
     (ruler-mode-default-face ((t (nil))))
     (ruler-mode-fill-column-face ((t (nil))))
     (ruler-mode-fringes-face ((t (nil))))
     (ruler-mode-goal-column-face ((t (nil))))
     (ruler-mode-margins-face ((t (nil))))
     (ruler-mode-pad-face ((t (nil))))
     (ruler-mode-tab-stop-face ((t (nil))))
     (scion-error-face ((t (:background "#f66" :foreground "white"))))
     (scion-filename-face ((t (:foreground "gray40"))))
     (scion-highlight-face ((t (:foreground "lightsteelblue1" :background "slateblue4" :underline nil))))
     (scion-warning-face ((t (:background "#fd9"))))
     (scroll-bar ((t (:background "grey18" :foreground "grey40" :box (:line-width 1 :color "grey26")))))
     (secondary-selection ((t (:background "aquamarine"))))
     (semantic-dirty-token-face ((t (:background "gray10"))))
     (semantic-intangible-face ((t (:foreground "gray25"))))
     (semantic-read-only-face ((t (:background "gray25"))))
     (semantic-unmatched-syntax-face ((t (:underline "red"))))
     (senator-intangible-face ((t (:foreground "gray75"))))
     (senator-momentary-highlight-face ((t (:background "slateblue4" :foreground "lightsteelblue1"))))
     (senator-read-only-face ((t (:background "#664444"))))
     (sgml-comment-face ((t (:foreground "dark turquoise"))))
     (sgml-doctype-face ((t (:foreground "turquoise"))))
     (sgml-end-tag-face ((t (:foreground "aquamarine"))))
     (sgml-entity-face ((t (:foreground "gray85"))))
     (sgml-ignored-face ((t (:background "gray60" :foreground "gray40"))))
     (sgml-ms-end-face ((t (:foreground "green"))))
     (sgml-ms-start-face ((t (:foreground "yellow"))))
     (sgml-namespace ((t (:foreground "gray57"))))
     (sgml-pi-face ((t (:foreground "lime green"))))
     (sgml-sgml-face ((t (:foreground "brown"))))
     (sgml-short-ref-face ((t (:foreground "deep sky blue"))))
     (sgml-start-tag-face ((t (:foreground "aquamarine"))))
     (sh-escaped-newline ((t (:foreground "gold"))))
     (sh-heredoc ((t (:bold t :foreground "yellow1" :weight bold))))
     (sh-heredoc-face ((t (:bold t :foreground "yellow1" :weight bold))))
     (sh-quoted-exec ((t (:foreground "cyan"))))
     (shadow ((t (nil))))
     (shell-option-face ((t (:foreground "NavajoWhite"))))
     (shell-output-2-face ((t (:foreground "gray85"))))
     (shell-output-3-face ((t (:foreground "gray85"))))
     (shell-output-face ((t (:bold t :weight bold))))
     (shell-prompt-face ((t (:foreground "VioletRed3"))))
     (show-paren-match ((t (:bold t :background "slateblue" :foreground "white" :weight bold))))
     (show-paren-mismatch ((t (:background "red" :foreground "yellow"))))
     (show-tabs-space-face ((t (:foreground "yellow"))))
     (show-tabs-tab-face ((t (:foreground "red"))))
     (show-trailing-whitespace ((t (nil))))
     (simple-wiki-bold-face ((t (:bold t :weight bold))))
     (simple-wiki-code-face ((t (nil))))
     (simple-wiki-emph-face ((t (:italic t :slant italic))))
     (simple-wiki-heading-1-face ((t (nil))))
     (simple-wiki-heading-2-face ((t (nil))))
     (simple-wiki-heading-3-face ((t (nil))))
     (simple-wiki-heading-4-face ((t (nil))))
     (simple-wiki-heading-5-face ((t (nil))))
     (simple-wiki-heading-6-face ((t (nil))))
     (simple-wiki-italic-face ((t (:italic t :slant italic))))
     (simple-wiki-local-link-face ((t (:foreground "gray80" :underline "gray50"))))
     (simple-wiki-nowiki-face ((t (nil))))
     (simple-wiki-smiley-face ((t (nil))))
     (simple-wiki-strike-face ((t (nil))))
     (simple-wiki-strong-emph-face ((t (:italic t :bold t :slant italic :weight bold))))
     (simple-wiki-strong-face ((t (:bold t :weight bold))))
     (simple-wiki-teletype-face ((t (nil))))
     (simple-wiki-underline-face ((t (nil))))
     (sldb-catch-tag-face ((t (nil))))
     (sldb-condition-face ((t (nil))))
     (sldb-detailed-frame-line-face ((t (nil))))
     (sldb-frame-label-face ((t (nil))))
     (sldb-frame-line-face ((t (nil))))
     (sldb-local-name-face ((t (nil))))
     (sldb-local-value-face ((t (nil))))
     (sldb-non-restartable-frame-line-face ((t (nil))))
     (sldb-reference-face ((t (:underline t))))
     (sldb-restart-face ((t (nil))))
     (sldb-restart-number-face ((t (:bold t :weight bold))))
     (sldb-restart-type-face ((t (:bold t :weight bold))))
     (sldb-restartable-frame-line-face ((t (:foreground "lime green"))))
     (sldb-section-face ((t (nil))))
     (sldb-topline-face ((t (nil))))
     (slime-error-face ((t (:bold t :foreground "red" :weight bold))))
     (slime-highlight-edits-face ((t (nil))))
     (slime-highlight-face ((t (nil))))
     (slime-inspector-action-face ((t (nil))))
     (slime-inspector-label-face ((t (nil))))
     (slime-inspector-topline-face ((t (nil))))
     (slime-inspector-type-face ((t (nil))))
     (slime-inspector-value-face ((t (nil))))
     (slime-note-face ((t (:foreground "gray40"))))
     (slime-reader-conditional-face ((t (nil))))
     (slime-repl-input-face ((t (:background "grey90"))))
     (slime-repl-inputed-output-face ((t (:foreground "red3"))))
     (slime-repl-output-face ((t (:foreground "gray60"))))
     (slime-repl-output-mouseover-face ((t (nil))))
     (slime-repl-prompt-face ((t (:bold t :foreground "RoyalBlue4" :background "lightsteelblue1" :weight bold))))
     (slime-repl-result-face ((t (:foreground "blue"))))
     (slime-style-warning-face ((t (nil))))
     (slime-warning-face ((t (:foreground "red"))))
     (smerge-base-face ((t (:foreground "red"))))
     (smerge-markers-face ((t (:background "grey85"))))
     (smerge-mine-face ((t (:foreground "Gray85"))))
     (smerge-other-face ((t (:foreground "darkgreen"))))
     (sml-yacc-bnf-face ((t (nil))))
     (spam-face ((t (:foreground "ivory2"))))
     (speedbar-button-face ((t (:foreground "seashell2"))))
     (speedbar-directory-face ((t (:foreground "seashell3"))))
     (speedbar-file-face ((t (:foreground "seashell4"))))
     (speedbar-highlight-face ((t (:background "dark slate blue" :foreground "wheat"))))
     (speedbar-selected-face ((t (:foreground "seashell1" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "antique white"))))
     (strokes-char-face ((t (:background "lightgray"))))
     (swbuff-current-buffer-face ((t (:bold t :foreground "gray85" :weight bold))))
     (table-cell-face ((t (:inverse-video nil))))
     (template-message-face ((t (:bold t :weight bold))))
     (term-black ((t (:foreground "black"))))
     (term-blackbg ((t (:background "black"))))
     (term-blue ((t (:foreground "blue"))))
     (term-bluebg ((t (:background "blue"))))
     (term-bold ((t (:bold t :weight bold))))
     (term-cyan ((t (:foreground "cyan"))))
     (term-cyanbg ((t (:background "cyan" :foreground "gray20"))))
     (term-default ((t (:background "gray80" :foreground "gray30" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :family "outline-lucida console"))))
     (term-default-bg ((t (nil))))
     (term-default-bg-inv ((t (nil))))
     (term-default-fg ((t (nil))))
     (term-default-fg-inv ((t (nil))))
     (term-green ((t (:foreground "green"))))
     (term-greenbg ((t (:background "green" :foreground "gray20"))))
     (term-invisible ((t (nil))))
     (term-invisible-inv ((t (nil))))
     (term-magenta ((t (:foreground "magenta"))))
     (term-magentabg ((t (:background "magenta" :foreground "gray20"))))
     (term-red ((t (:foreground "red"))))
     (term-redbg ((t (:background "red" :foreground "gray20"))))
     (term-underline ((t (:underline t))))
     (term-white ((t (:foreground "white"))))
     (term-whitebg ((t (:background "white" :foreground "gray20"))))
     (term-yellow ((t (:foreground "yellow"))))
     (term-yellowbg ((t (:background "yellow" :foreground "gray20"))))
     (tex-math-face ((t (:foreground "RosyBrown"))))
     (texinfo-heading-face ((t (:foreground "Blue"))))
     (text-cursor ((t (:background "Red3" :foreground "gray80"))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "#f99"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "Optima"))))
     (vc-annotate-face-0046FF ((t (:background "black" :foreground "wheat"))))
     (vcursor ((t (:background "cyan" :foreground "blue" :underline t))))
     (vertical-border ((t (nil))))
     (vertical-divider ((t (:background "Gray80"))))
     (vhdl-font-lock-attribute-face ((t (:foreground "gray85"))))
     (vhdl-font-lock-directive-face ((t (:foreground "gray85"))))
     (vhdl-font-lock-enumvalue-face ((t (:foreground "gray85"))))
     (vhdl-font-lock-function-face ((t (:foreground "gray85"))))
     (vhdl-font-lock-prompt-face ((t (:bold t :foreground "gray85" :weight bold))))
     (vhdl-font-lock-reserved-words-face ((t (:bold t :foreground "gray85" :weight bold))))
     (vhdl-font-lock-translate-off-face ((t (:background "LightGray"))))
     (vhdl-speedbar-architecture-face ((t (:foreground "gray85"))))
     (vhdl-speedbar-architecture-selected-face ((t (:foreground "gray85" :underline t))))
     (vhdl-speedbar-configuration-face ((t (:foreground "gray85"))))
     (vhdl-speedbar-configuration-selected-face ((t (:foreground "gray85" :underline t))))
     (vhdl-speedbar-entity-face ((t (:foreground "gray85"))))
     (vhdl-speedbar-entity-selected-face ((t (:foreground "gray85" :underline t))))
     (vhdl-speedbar-instantiation-face ((t (:foreground "gray85"))))
     (vhdl-speedbar-instantiation-selected-face ((t (:foreground "gray85" :underline t))))
     (vhdl-speedbar-package-face ((t (:foreground "gray85"))))
     (vhdl-speedbar-package-selected-face ((t (:foreground "gray85" :underline t))))
     (viper-minibuffer-emacs-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-minibuffer-insert-face ((t (:background "pink" :foreground "Black"))))
     (viper-minibuffer-vi-face ((t (:background "grey" :foreground "DarkGreen"))))
     (viper-replace-overlay-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-search-face ((t (:background "khaki" :foreground "Black"))))
     (vm-header-content-face ((t (:italic t :foreground "wheat" :slant italic))))
     (vm-header-from-face ((t (:italic t :foreground "wheat" :slant italic))))
     (vm-header-name-face ((t (:foreground "cyan"))))
     (vm-header-subject-face ((t (:foreground "cyan"))))
     (vm-header-to-face ((t (:italic t :foreground "cyan" :slant italic))))
     (vm-message-cited-face ((t (:foreground "Gray80"))))
     (vm-monochrome-image ((t (:background "white" :foreground "gray30"))))
     (vm-summary-face-1 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-2 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-3 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-4 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-highlight-face ((t (:foreground "White"))))
     (vm-xface ((t (:background "white" :foreground "gray30"))))
     (vmpc-pre-sig-face ((t (:foreground "gray85"))))
     (vmpc-sig-face ((t (:foreground "gray85"))))
     (vvb-face ((t (:background "pink" :foreground "gray30"))))
     (w3m-anchor-face ((t (:foreground "gray80" :underline "gray50"))))
     (w3m-arrived-anchor-face ((t (nil))))
     (w3m-bold-face ((t (nil))))
     (w3m-current-anchor-face ((t (nil))))
     (w3m-form-button-face ((t (nil))))
     (w3m-form-button-mouse-face ((t (nil))))
     (w3m-form-button-pressed-face ((t (nil))))
     (w3m-form-face ((t (nil))))
     (w3m-header-line-location-content-face ((t (nil))))
     (w3m-header-line-location-title-face ((t (nil))))
     (w3m-history-current-url-face ((t (nil))))
     (w3m-image-face ((t (nil))))
     (w3m-strike-through-face ((t (nil))))
     (w3m-tab-background-face ((t (nil))))
     (w3m-tab-selected-face ((t (nil))))
     (w3m-tab-selected-retrieving-face ((t (nil))))
     (w3m-tab-unselected-face ((t (nil))))
     (w3m-tab-unselected-retrieving-face ((t (nil))))
     (w3m-underline-face ((t (nil))))
     (white ((t (:foreground "white"))))
     (whitespace-highlight-face ((t (nil))))
     (widget ((t (nil))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "light blue"))))
     (widget-field ((t (:background "dim gray" :foreground "white"))))
     (widget-inactive ((t (:foreground "light gray"))))
     (widget-single-line-field ((t (:background "slate gray" :foreground "gray30"))))
     (woman-addition-face ((t (:foreground "orange"))))
     (woman-bold-face ((t (:bold t :foreground "sky blue" :weight bold))))
     (woman-italic-face ((t (:foreground "deep sky blue"))))
     (woman-unknown-face ((t (:foreground "LightSalmon"))))
     (x-face ((t (:background "white" :foreground "gray30"))))
     (xrdb-option-name-face ((t (:foreground "gray85"))))
     (xref-keyword-face ((t (:foreground "gray85"))))
     (xref-list-default-face ((t (nil))))
     (xref-list-pilot-face ((t (:foreground "gray85"))))
     (xref-list-symbol-face ((t (:foreground "navy"))))
     (xsl-fo-alternate-face ((t (:foreground "Yellow"))))
     (xsl-fo-main-face ((t (:foreground "PaleGreen"))))
     (xsl-other-element-face ((t (:foreground "Coral"))))
     (xsl-xslt-alternate-face ((t (:foreground "LightGray"))))
     (xsl-xslt-main-face ((t (:foreground "Wheat"))))
     (xxml-emph-1-face ((t (:background "lightyellow"))))
     (xxml-emph-2-face ((t (:background "lightyellow"))))
     (xxml-header-1-face ((t (:background "seashell1" :foreground "MediumAquamarine"))))
     (xxml-header-2-face ((t (:background "seashell1" :foreground "SkyBlue"))))
     (xxml-header-3-face ((t (:background "seashell1"))))
     (xxml-header-4-face ((t (:background "seashell1"))))
     (xxml-interaction-face ((t (:background "lightcyan"))))
     (xxml-rug-face ((t (:background "cyan"))))
     (xxml-sparkle-face ((t (:background "yellow"))))
     (xxml-unbreakable-space-face ((t (:foreground "grey" :underline t))))
     (yellow ((t (:foreground "yellow"))))
     (zmacs-region ((t (:background "grey30")))))))
(add-to-list 'color-themes '(color-theme-mac-novel  "Mac Novel" "nominolo"))
